let me=null;
const app=document.getElementById("app");
async function api(url,opt={}){let r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"حدث خطأ");return d}
function logout(){localStorage.removeItem("me");me=null;render()}
function loginPage(){app.innerHTML=`<div class="login"><h1>بوابة مدرسة التعليم البريطاني</h1><input id="u" placeholder="اسم المستخدم"><input id="p" type="password" placeholder="كلمة المرور"><button onclick="login()">دخول</button><div class="notice">للتجربة: admin / 1234 أو teacher / 1234 أو parent / 1234</div></div>`}
async function login(){try{me=await api("/api/login",{method:"POST",body:JSON.stringify({username:u.value,password:p.value})});localStorage.setItem("me",JSON.stringify(me));render()}catch(e){alert(e.message)}}
async function render(){if(!me){loginPage();return}if(me.role==="admin")return admin();if(me.role==="teacher")return teacher();return family()}
async function admin(){let s=await api("/api/students");app.innerHTML=`<div class="wrap"><h1>لوحة الإدارة</h1><div class="cards"><div class="card">الطلاب<div class="num">${s.length}</div></div><div class="card">الحاضرون<div class="num">${s.filter(x=>x.status==="حاضر").length}</div></div><div class="card">الغائبون<div class="num">${s.filter(x=>x.status==="غائب").length}</div></div></div><h2>الطلاب</h2><table class="table"><tr><th>الاسم</th><th>الفصل</th><th>الحالة</th><th>WhatsApp ولي الأمر</th></tr>${s.map(x=>`<tr><td>${x.name}</td><td>${x.class_name}</td><td>${x.status}</td><td>${x.parent_phone}</td></tr>`).join("")}</table><h2>إضافة طالب</h2><div class="form row"><input id="sn" placeholder="اسم الطالب"><input id="sc" placeholder="الفصل"><input id="sp" placeholder="رقم WhatsApp ولي الأمر"><button onclick="addStudent()">إضافة</button></div></div>`}
async function addStudent(){try{await api("/api/students",{method:"POST",body:JSON.stringify({name:sn.value,class_name:sc.value,parent_phone:sp.value})});admin()}catch(e){alert(e.message)}}
async function teacher(){let s=await api("/api/students");app.innerHTML=`<div class="wrap"><h1>بوابة المدرس</h1><div class="card"><h2>الحضور</h2><table class="table"><tr><th>الطالب</th><th>الفصل</th><th>الحالة</th><th></th></tr>${s.map(x=>`<tr><td>${x.name}</td><td>${x.class_name}</td><td>${x.status}</td><td><button onclick="toggleStatus(${x.id})">تغيير</button></td></tr>`).join("")}</table></div><div class="form"><h2>ملاحظة لولي الأمر</h2><select id="sid">${s.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}</select><textarea id="nt" placeholder="اكتب الملاحظة اليومية"></textarea><button onclick="note()">حفظ وإرسال عبر WhatsApp</button><div class="msg">سيتم إرسال الرسالة فعلياً بعد إضافة بيانات WhatsApp Business API في الخادم.</div></div><div class="form"><h2>فيديو الحصة</h2><input id="vt" placeholder="اسم المادة والحصة"><input id="vf" type="file" accept="video/*"><button onclick="video()">حفظ بيانات الفيديو</button></div></div>`}
async function toggleStatus(id){await api("/api/students/"+id+"/status",{method:"PATCH"});teacher()}
async function note(){try{await api("/api/notes",{method:"POST",body:JSON.stringify({student_id:+sid.value,text:nt.value})});alert("تم حفظ الملاحظة وتجهيزها للربط مع WhatsApp");teacher()}catch(e){alert(e.message)}}
async function video(){if(!vt.value)return alert("اكتب اسم الحصة");let f=vf.files[0];await api("/api/videos",{method:"POST",body:JSON.stringify({title:vt.value,file_name:f?f.name:""})});alert("تم حفظ بيانات الحصة. رفع الملف الفعلي يحتاج تخزيناً سحابياً.");}
async function family(){let s=(await api("/api/students"))[0],n=await api("/api/notes/"+s.id),v=await api("/api/videos");app.innerHTML=`<div class="wrap"><h1>بوابة ولي الأمر</h1><div class="cards"><div class="card">الطالب<div class="num">${s.name}</div><p>${s.class_name}</p></div><div class="card">الحضور اليوم<div class="num">${s.status}</div></div></div><h2>ملاحظات المدرسة</h2>${n.map(x=>`<div class="notice"><b>${x.created_at}</b><br>${x.text}<br><small>📱 جاهزة للإرسال عبر WhatsApp بعد الربط</small></div>`).join("")||'<div class="card">لا توجد ملاحظات.</div>'}<h2>الحصص</h2>${v.map(x=>`<div class="card">🎥 ${x.title}<br><small>${x.created_at}</small></div>`).join("")||'<div class="card">لا توجد حصص.</div>'}</div>`}
me=JSON.parse(localStorage.getItem("me")||"null");render()
