const fs = require('fs');
const path = require('path');

const src = fs.readFileSync(path.join(__dirname, 'server.js'), 'utf8');
const rolesBlock = `const ROLES = {
 PROGRAMMER:'مبرمج النظام', ADMIN:'مدير المدرسة', DEPUTY:'نائب مدير المدرسة', ACADEMIC_DIRECTOR:'المدير الأكاديمي', ADMIN_DIRECTOR:'المدير الإداري', ACADEMIC_SUPERVISOR:'مشرف أكاديمي', EDUCATIONAL_SUPERVISOR:'مشرف تربوي', ADMIN_SUPERVISOR:'مشرف إداري', DEPARTMENT_HEAD:'رئيس قسم', COORDINATOR:'منسق أكاديمي', TEACHER:'معلم', SENIOR_TEACHER:'معلم أول', ASSISTANT_TEACHER:'معلم مساعد', SUBSTITUTE_TEACHER:'مدرس بديل', STUDENT_AFFAIRS:'مسؤول شؤون الطلاب', ADMISSIONS:'مسؤول التسجيل والقبول', ATTENDANCE:'مسؤول الحضور والغياب', ACTIVITIES:'مسؤول الأنشطة الطلابية', COUNSELOR:'مرشد طلابي', FINANCE_MANAGER:'مدير مالي', ACCOUNTANT:'محاسب', FEES_OFFICER:'مسؤول الرسوم الدراسية', CASHIER:'أمين صندوق', QUALITY_MANAGER:'مدير الجودة', QUALITY_OFFICER:'مسؤول الجودة', ASSESSMENT:'مسؤول التقييم والمتابعة', OPERATIONS:'مسؤول العمليات', HR:'مسؤول الموارد البشرية', IT:'مسؤول تقنية المعلومات', FACILITIES:'مسؤول المرافق', LIBRARIAN:'أمين مكتبة', TRANSPORT:'مسؤول النقل المدرسي', SAFETY:'مسؤول الأمن والسلامة', PARENT:'ولي أمر', STUDENT:'طالب', LEGACY_ADMIN:'مدير', LEGACY_OPERATIONS:'عمليات', LEGACY_QUALITY:'جودة', LEGACY_SUPERVISOR:'مشرف'
};
const ALL_ROLES = [...new Set(Object.values(ROLES))];`;
let code = src.replace(/const ROLES = \{[\s\S]*?const ALL_ROLES = Object\.values\(ROLES\);/, rolesBlock);

const addon = `
/* ===== SCHOOL PORTAL ENHANCEMENTS ===== */
const ROLE_GROUPS = {
 'الإدارة العليا':['مبرمج النظام','مدير المدرسة','نائب مدير المدرسة','المدير الأكاديمي','المدير الإداري'],
 'الإشراف والإدارة التعليمية':['مشرف أكاديمي','مشرف تربوي','مشرف إداري','رئيس قسم','منسق أكاديمي'],
 'التدريس':['معلم','معلم أول','معلم مساعد','مدرس بديل'],
 'شؤون الطلاب':['مسؤول شؤون الطلاب','مسؤول التسجيل والقبول','مسؤول الحضور والغياب','مسؤول الأنشطة الطلابية','مرشد طلابي'],
 'المالية':['مدير مالي','محاسب','مسؤول الرسوم الدراسية','أمين صندوق'],
 'الجودة':['مدير الجودة','مسؤول الجودة','مسؤول التقييم والمتابعة'],
 'العمليات والخدمات':['مسؤول العمليات','مسؤول الموارد البشرية','مسؤول تقنية المعلومات','مسؤول المرافق','أمين مكتبة','مسؤول النقل المدرسي','مسؤول الأمن والسلامة'],
 'أولياء الأمور والطلاب':['ولي أمر','طالب']
};
const PERMS=['dashboard','users','roles','students','parents','attendance','grades','notes','fees','reports','quality','settings'];
db.exec(\`
CREATE TABLE IF NOT EXISTS role_permissions(role TEXT NOT NULL,permission TEXT NOT NULL,allowed INTEGER DEFAULT 0,PRIMARY KEY(role,permission));
CREATE TABLE IF NOT EXISTS fees(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,description TEXT NOT NULL,amount REAL DEFAULT 0,due_date TEXT,status TEXT DEFAULT 'مستحق',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS fee_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,fee_id INTEGER NOT NULL,amount REAL DEFAULT 0,payment_date TEXT DEFAULT CURRENT_TIMESTAMP,method TEXT,reference TEXT,created_by INTEGER,FOREIGN KEY(fee_id) REFERENCES fees(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS grade_results(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,subject_id INTEGER,term TEXT,assessment TEXT,score REAL DEFAULT 0,max_score REAL DEFAULT 100,remarks TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS attendance_records(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,attendance_date TEXT NOT NULL,status TEXT DEFAULT 'حاضر',reason TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(student_id,attendance_date),FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
\`);
const roleDefaults={
 'مبرمج النظام':PERMS,'مدير المدرسة':['dashboard','users','students','parents','attendance','grades','notes','fees','reports','quality'],'ولي أمر':['dashboard','students','attendance','grades','notes','fees'],'طالب':['dashboard','students','attendance','grades','notes']
};
const rp=db.prepare('INSERT OR IGNORE INTO role_permissions(role,permission,allowed) VALUES(?,?,?)');
for(const role of Object.values(ROLE_GROUPS).flat()) for(const p of PERMS) rp.run(role,p,(roleDefaults[role]||roleDefaults['مدير المدرسة']).includes(p)?1:0);
function hasPerm(user,p){ if(!user)return false; if(user.role==='مبرمج النظام'||user.role==='مبرمج')return true; const x=db.prepare('SELECT allowed FROM role_permissions WHERE role=? AND permission=?').get(user.role,p); return !!(x&&x.allowed); }
function need(p){return (req,res,next)=>hasPerm(req.user,p)?next():res.status(403).json({success:false,message:'ليس لديك صلاحية لهذا الإجراء'});}

app.get('/api/roles',auth,(req,res)=>{if(!hasPerm(req.user,'roles'))return res.status(403).json({success:false,message:'غير مصرح'});res.json({success:true,groups:ROLE_GROUPS,roles:Object.values(ROLE_GROUPS).flat(),permissions:PERMS});});
app.get('/api/roles/:role/permissions',auth,(req,res)=>{if(!hasPerm(req.user,'roles'))return res.status(403).json({success:false,message:'غير مصرح'});res.json({success:true,permissions:db.prepare('SELECT permission,allowed FROM role_permissions WHERE role=?').all(req.params.role)});});
app.put('/api/roles/:role/permissions',auth,(req,res)=>{if(!hasPerm(req.user,'roles'))return res.status(403).json({success:false,message:'غير مصرح'});const q=db.prepare('INSERT INTO role_permissions(role,permission,allowed) VALUES(?,?,?) ON CONFLICT(role,permission) DO UPDATE SET allowed=excluded.allowed');for(const [p,v] of Object.entries(req.body.permissions||{}))q.run(req.params.role,p,v?1:0);res.json({success:true,message:'تم تحديث الصلاحيات'});});

app.get('/api/parent/dashboard',auth,need('dashboard'),(req,res)=>{if(req.user.role!=='ولي أمر')return res.status(403).json({success:false,message:'هذه الصفحة لولي الأمر'});const students=db.prepare('SELECT s.* FROM students s JOIN student_parents sp ON sp.student_id=s.id JOIN parents p ON p.id=sp.parent_id WHERE p.user_id=? ORDER BY s.full_name').all(req.user.id);const data=students.map(s=>{const fees=db.prepare('SELECT f.*,COALESCE((SELECT SUM(amount) FROM fee_payments WHERE fee_id=f.id),0) paid FROM fees f WHERE f.student_id=?').all(s.id);const results=db.prepare('SELECT g.*,s.name subject_name FROM grade_results g LEFT JOIN subjects s ON s.id=g.subject_id WHERE g.student_id=? ORDER BY g.created_at DESC').all(s.id);const attendance=db.prepare('SELECT * FROM attendance_records WHERE student_id=? ORDER BY attendance_date DESC LIMIT 100').all(s.id);const notes=db.prepare('SELECT n.*,u.full_name creator_name,t.full_name teacher_name FROM notes n LEFT JOIN users u ON u.id=n.created_by LEFT JOIN users t ON t.id=n.teacher_id WHERE n.student_id=? AND n.visible_to_parent=1 ORDER BY n.created_at DESC').all(s.id);const total=fees.reduce((a,f)=>a+Number(f.amount||0),0),paid=fees.reduce((a,f)=>a+Number(f.paid||0),0);return {...s,fees,results,attendance,notes,financial:{total,paid,remaining:Math.max(0,total-paid)}}});res.json({success:true,students:data});});

app.get('/api/parent/students/:id',auth,(req,res)=>{if(req.user.role!=='ولي أمر')return res.status(403).json({success:false,message:'غير مصرح'});const id=Number(req.params.id);if(!db.prepare('SELECT 1 FROM student_parents sp JOIN parents p ON p.id=sp.parent_id WHERE sp.student_id=? AND p.user_id=?').get(id,req.user.id))return res.status(403).json({success:false,message:'هذا الطالب ليس من أبنائك'});const student=db.prepare('SELECT * FROM students WHERE id=?').get(id);const fees=db.prepare('SELECT f.*,COALESCE((SELECT SUM(amount) FROM fee_payments WHERE fee_id=f.id),0) paid FROM fees f WHERE f.student_id=?').all(id);const results=db.prepare('SELECT g.*,s.name subject_name FROM grade_results g LEFT JOIN subjects s ON s.id=g.subject_id WHERE g.student_id=? ORDER BY g.created_at DESC').all(id);const attendance=db.prepare('SELECT * FROM attendance_records WHERE student_id=? ORDER BY attendance_date DESC').all(id);const notes=db.prepare('SELECT n.*,u.full_name creator_name,t.full_name teacher_name FROM notes n LEFT JOIN users u ON u.id=n.created_by LEFT JOIN users t ON t.id=n.teacher_id WHERE n.student_id=? AND n.visible_to_parent=1 ORDER BY n.created_at DESC').all(id);res.json({success:true,student,fees,results,attendance,notes});});

app.post('/api/fees',auth,need('fees'),(req,res)=>{const {student_id,description,amount,due_date}=req.body;if(!student_id||!description)return res.status(400).json({success:false,message:'بيانات الرسوم ناقصة'});const r=db.prepare('INSERT INTO fees(student_id,description,amount,due_date) VALUES(?,?,?,?)').run(student_id,description,Number(amount||0),due_date||null);notifyParentsOfStudent(Number(student_id),'رسوم دراسية جديدة',`تمت إضافة رسوم ${description} بقيمة ${Number(amount||0)}`,'fee');res.json({success:true,fee_id:r.lastInsertRowid,message:'تمت إضافة الرسوم'});});
app.post('/api/fees/:id/payment',auth,need('fees'),(req,res)=>{const id=Number(req.params.id),amount=Number(req.body.amount||0);if(amount<=0)return res.status(400).json({success:false,message:'قيمة الدفع غير صحيحة'});db.prepare('INSERT INTO fee_payments(fee_id,amount,method,reference,created_by) VALUES(?,?,?,?,?)').run(id,amount,req.body.method||'',req.body.reference||'',req.user.id);const f=db.prepare('SELECT amount,(SELECT COALESCE(SUM(amount),0) FROM fee_payments WHERE fee_id=?) paid FROM fees WHERE id=?').get(id,id);if(f&&f.paid>=f.amount)db.prepare("UPDATE fees SET status='مدفوع' WHERE id=?").run(id);res.json({success:true,message:'تم تسجيل الدفعة'});});
app.post('/api/grades',auth,need('grades'),(req,res)=>{const {student_id,subject_id,term,assessment,score,max_score,remarks}=req.body;if(!student_id||score===undefined)return res.status(400).json({success:false,message:'بيانات النتيجة ناقصة'});const r=db.prepare('INSERT INTO grade_results(student_id,subject_id,term,assessment,score,max_score,remarks) VALUES(?,?,?,?,?,?,?)').run(student_id,subject_id||null,term||'',assessment||'',Number(score),Number(max_score||100),remarks||'');notifyParentsOfStudent(Number(student_id),'نتيجة جديدة',`تم تسجيل نتيجة جديدة في ${assessment||'اختبار'}`,'grade');res.json({success:true,result_id:r.lastInsertRowid,message:'تم حفظ النتيجة'});});
app.post('/api/attendance',auth,need('attendance'),(req,res)=>{const {student_id,attendance_date,status,reason}=req.body;if(!student_id||!attendance_date)return res.status(400).json({success:false,message:'بيانات الحضور ناقصة'});db.prepare('INSERT INTO attendance_records(student_id,attendance_date,status,reason,created_by) VALUES(?,?,?,?,?) ON CONFLICT(student_id,attendance_date) DO UPDATE SET status=excluded.status,reason=excluded.reason,created_by=excluded.created_by').run(student_id,attendance_date,status||'حاضر',reason||'',req.user.id);if(status&&status!=='حاضر')notifyParentsOfStudent(Number(student_id),'تحديث الحضور والغياب',`تم تسجيل حالة ${status} بتاريخ ${attendance_date}`,'attendance');res.json({success:true,message:'تم تحديث الحضور'});});

app.get('/api/parent/notifications',auth,(req,res)=>{if(req.user.role!=='ولي أمر')return res.status(403).json({success:false,message:'غير مصرح'});res.json({success:true,notifications:db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(req.user.id)});});
`;
const marker='/* =========================================================\n   STATIC FILES\n========================================================= */';
code=code.replace(marker,addon+'\n'+marker);
fs.writeFileSync(path.join(__dirname,'.server-runtime.js'),code,'utf8');
require('./.server-runtime.js');
