const Module=require('module');
const Database=require('better-sqlite3');
const path=require('path');
const previous=Module._load;
const db=new Database(path.join(__dirname,'school.db'));
db.pragma('journal_mode=WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS platform_settings(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS schools(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,logo_url TEXT DEFAULT '',status TEXT DEFAULT 'pending',owner_approved INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS school_access_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,school_id INTEGER NOT NULL,manager_user_id INTEGER NOT NULL,status TEXT DEFAULT 'pending',owner_note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
`);
const defaults={platform_name:'EduCore Platform',platform_tagline:'منصة متكاملة لإدارة المدارس والمؤسسات التعليمية',primary_color:'#1457c7',secondary_color:'#082d67',accent_color:'#2b70da',surface_color:'#ffffff',background_color:'#f7f9fc',logo_url:'',login_title:'مرحباً بك في EduCore Platform',login_subtitle:'أدخل بيانات حسابك للوصول إلى بيئة مدرستك بأمان.',support_email:'',support_phone:'',footer_text:'EduCore Platform · 2026',maintenance_mode:'0'};
for(const [k,v] of Object.entries(defaults))db.prepare('INSERT OR IGNORE INTO platform_settings(key,value) VALUES(?,?)').run(k,v);
function settings(){const rows=db.prepare('SELECT key,value FROM platform_settings').all();return Object.fromEntries(rows.map(x=>[x.key,x.value]));}
function slugify(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)}
let capturedAuth=null;
Module._load=function(){const loaded=previous.apply(this,arguments);if(arguments[0]!=='express')return loaded;const wrapped=function(){const app=loaded();const originalUse=app.use.bind(app);app.use=function(...args){for(const fn of args){if(typeof fn==='function'&&fn.name==='auth')capturedAuth=fn;}return originalUse(...args)};setImmediate(()=>{if(app.__ownerRoutes)return;app.__ownerRoutes=true;
const owner=(req,res,next)=>{if(!req.user||!['مبرمج','مبرمج النظام','مالك المنصة','owner'].includes(req.user.role))return res.status(403).json({success:false,message:'هذه المنطقة مخصصة لمالك المنصة'});next()};
const guard=(req,res,next)=>{if(capturedAuth)return capturedAuth(req,res,next);return res.status(503).json({success:false,message:'نظام الدخول غير جاهز'});};
app.get('/api/public/platform-settings',(req,res)=>res.json({success:true,settings:settings()}));
app.get('/api/owner/platform-settings',guard,owner,(req,res)=>res.json({success:true,settings:settings()}));
app.put('/api/owner/platform-settings',guard,owner,(req,res)=>{try{const allowed=new Set(Object.keys(defaults));const input=req.body||{};const tx=db.transaction(()=>{for(const [k,v] of Object.entries(input)){if(!allowed.has(k))continue;const value=String(v??'').slice(0,2000);db.prepare("INSERT INTO platform_settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").run(k,value)}});tx();res.json({success:true,message:'تم حفظ إعدادات المنصة',settings:settings()})}catch(e){console.error(e);res.status(400).json({success:false,message:'تعذر حفظ الإعدادات'})}});
app.post('/api/owner/platform-settings/reset',guard,owner,(req,res)=>{const tx=db.transaction(()=>{for(const [k,v] of Object.entries(defaults))db.prepare("INSERT INTO platform_settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").run(k,v)});tx();res.json({success:true,settings:settings()})});
app.get('/api/owner/overview',guard,owner,(req,res)=>{const counts={users:db.prepare('SELECT COUNT(*) c FROM users').get().c,schools:db.prepare('SELECT COUNT(*) c FROM schools').get().c,students:db.prepare('SELECT COUNT(*) c FROM students').get().c,parents:db.prepare('SELECT COUNT(*) c FROM parents').get().c};res.json({success:true,counts})});
app.get('/api/owner/schools',guard,owner,(req,res)=>{const rows=db.prepare(`SELECT s.id,s.name,s.slug,s.status,s.owner_approved,s.created_at,u.id manager_user_id,u.username manager_username,u.full_name manager_name,u.email manager_email,u.active manager_active FROM schools s LEFT JOIN school_access_requests r ON r.school_id=s.id AND r.id=(SELECT MAX(r2.id) FROM school_access_requests r2 WHERE r2.school_id=s.id) LEFT JOIN users u ON u.id=r.manager_user_id ORDER BY s.created_at DESC`).all();res.json({success:true,schools:rows})});
app.post('/api/owner/schools',guard,owner,(req,res)=>{try{const name=String(req.body?.name||'').trim();if(name.length<2)return res.status(400).json({success:false,message:'اسم المدرسة مطلوب'});let slug=slugify(req.body?.slug||name)||`school-${Date.now()}`;let base=slug,n=2;while(db.prepare('SELECT id FROM schools WHERE slug=?').get(slug))slug=`${base}-${n++}`;const logo=String(req.body?.logo_url||'').trim().slice(0,1000);const result=db.prepare("INSERT INTO schools(name,slug,logo_url,status,owner_approved) VALUES(?,?,?,'active',1)").run(name,slug,logo);const school=db.prepare('SELECT * FROM schools WHERE id=?').get(result.lastInsertRowid);res.status(201).json({success:true,message:'تم إنشاء المدرسة وتفعيلها بنجاح',school})}catch(e){console.error(e);res.status(400).json({success:false,message:'تعذر إنشاء المدرسة'})}});
app.patch('/api/owner/schools/:id',guard,owner,(req,res)=>{const sid=Number(req.params.id);const school=db.prepare('SELECT * FROM schools WHERE id=?').get(sid);if(!school)return res.status(404).json({success:false,message:'المدرسة غير موجودة'});const name=String(req.body?.name??school.name).trim();if(name.length<2)return res.status(400).json({success:false,message:'اسم المدرسة مطلوب'});const logo=String(req.body?.logo_url??school.logo_url).trim().slice(0,1000);db.prepare('UPDATE schools SET name=?,logo_url=? WHERE id=?').run(name,logo,sid);res.json({success:true,message:'تم تحديث بيانات المدرسة',school:db.prepare('SELECT * FROM schools WHERE id=?').get(sid)})});
app.post('/api/owner/schools/:id/approve',guard,owner,(req,res)=>{const sid=Number(req.params.id);const school=db.prepare('SELECT * FROM schools WHERE id=?').get(sid);if(!school)return res.status(404).json({success:false,message:'المدرسة غير موجودة'});const request=db.prepare('SELECT * FROM school_access_requests WHERE school_id=? ORDER BY id DESC LIMIT 1').get(sid);const tx=db.transaction(()=>{db.prepare("UPDATE schools SET status='active',owner_approved=1 WHERE id=?").run(sid);if(request){db.prepare("UPDATE school_access_requests SET status='approved',owner_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body?.owner_note||'تم اعتماد المدرسة',request.id);db.prepare('UPDATE users SET active=1,must_change_password=0 WHERE id=?').run(request.manager_user_id)}});tx();res.json({success:true,message:'تم اعتماد المدرسة وتفعيل حساب مديرها'});});
app.post('/api/owner/schools/:id/reject',guard,owner,(req,res)=>{const sid=Number(req.params.id);const school=db.prepare('SELECT * FROM schools WHERE id=?').get(sid);if(!school)return res.status(404).json({success:false,message:'المدرسة غير موجودة'});const request=db.prepare('SELECT * FROM school_access_requests WHERE school_id=? ORDER BY id DESC LIMIT 1').get(sid);const tx=db.transaction(()=>{db.prepare("UPDATE schools SET status='rejected',owner_approved=0 WHERE id=?").run(sid);if(request){db.prepare("UPDATE school_access_requests SET status='rejected',owner_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body?.owner_note||'تم رفض الطلب',request.id);db.prepare('UPDATE users SET active=0 WHERE id=?').run(request.manager_user_id)}});tx();res.json({success:true,message:'تم رفض طلب المدرسة'});});
app.get('/api/owner/school/:id/users',guard,owner,(req,res)=>{const sid=Number(req.params.id);if(!db.prepare('SELECT id FROM schools WHERE id=?').get(sid))return res.status(404).json({success:false,message:'المدرسة غير موجودة'});const users=db.prepare("SELECT id,username,full_name,email,phone,role,active,must_change_password,created_at FROM users WHERE school_id=? ORDER BY created_at DESC").all(sid);res.json({success:true,users})});
app.patch('/api/owner/users/:id/status',guard,owner,(req,res)=>{const id=Number(req.params.id);const active=req.body?.active?1:0;const user=db.prepare('SELECT id,school_id FROM users WHERE id=?').get(id);if(!user)return res.status(404).json({success:false,message:'المستخدم غير موجود'});db.prepare('UPDATE users SET active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(active,id);res.json({success:true,message:active?'تم تفعيل المستخدم':'تم إيقاف المستخدم'})});
});return app};Object.setPrototypeOf(wrapped,loaded);wrapped.prototype=loaded.prototype;for(const k of Object.keys(loaded))wrapped[k]=loaded[k];wrapped.__ownerAdminWrapped=true;return wrapped};
