const path=require('path');const fs=require('fs');const Database=require('better-sqlite3');const Module=require('module');const originalLoad=Module._load;const DB_PATH=path.join(__dirname,'school.db');
Module._load=function(request,parent,isMain){const loaded=originalLoad.apply(this,arguments);if(request!=='express')return loaded;function wrappedExpress(){const app=loaded();const db=new Database(DB_PATH);db.pragma('foreign_keys=ON');
for(const table of ['users','students','parents','classes','subjects','lessons','notes','teacher_notes','messages','notifications']){try{const cols=db.prepare(`PRAGMA table_info(${table})`).all().map(x=>x.name);if(!cols.includes('school_id'))db.exec(`ALTER TABLE ${table} ADD COLUMN school_id INTEGER`)}catch{}}
const first=db.prepare('SELECT id FROM schools ORDER BY id LIMIT 1').get();if(first){for(const table of ['users','students','parents','classes','subjects','lessons','notes','teacher_notes','messages','notifications']){try{db.prepare(`UPDATE ${table} SET school_id=? WHERE school_id IS NULL`).run(first.id)}catch{}}}
const findSession=token=>global.__educoreSessions?.get(token);const owner=req=>{const s=findSession((req.headers.authorization||'').replace(/^Bearer\s+/,''));if(!s)return null;return db.prepare('SELECT id,role,school_id FROM users WHERE id=?').get(s.userId)};
app.use('/api',(req,res,next)=>{if(!req.headers['x-school-id'])return next();const u=owner(req);if(!u)return next();const target=Number(req.headers['x-school-id']);if(u.role==='مبرمج')return next();if(!u.school_id||u.school_id!==target)return res.status(403).json({success:false,message:'الوصول إلى بيانات مدرسة أخرى غير مسموح'});next()});
app.get('/api/security/audit',(req,res)=>{const u=owner(req);if(!u)return res.status(401).json({success:false,message:'يجب تسجيل الدخول أولاً'});if(u.role!=='مبرمج')return res.status(403).json({success:false,message:'صلاحية المبرمج مطلوبة'});const limit=Math.min(500,Math.max(1,Number(req.query.limit||100)));res.json({success:true,logs:db.prepare('SELECT a.*,u.username,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT ?').all(limit)})});
app.get('/api/security/tenant-check',(req,res)=>{const u=owner(req);if(!u)return res.status(401).json({success:false,message:'يجب تسجيل الدخول أولاً'});if(u.role!=='مبرمج')return res.status(403).json({success:false,message:'صلاحية المبرمج مطلوبة'});const schools=db.prepare('SELECT id,name,code,status FROM schools ORDER BY id').all();const counts={};for(const t of ['users','students','parents','classes','subjects','lessons','notes','teacher_notes','messages','notifications']){try{counts[t]=db.prepare(`SELECT school_id,COUNT(*) count FROM ${t} GROUP BY school_id ORDER BY school_id`).all()}catch{counts[t]=[]}}res.json({success:true,schools,counts})});
return app}return wrappedExpress};
