const http=require('http');const fs=require('fs');const path=require('path');const {spawn}=require('child_process');
const PUBLIC_PORT=Number(process.env.PORT||8080);const BACKEND_PORT=Number(process.env.BACKEND_PORT||8081);const ROOT=__dirname;
const preload=['enhanced.js','role-users.js','parent-extra.js','saas.js'];
const args=preload.filter(f=>fs.existsSync(path.join(ROOT,f))).flatMap(f=>['-r',path.join(ROOT,f)]);args.push(path.join(ROOT,'server.js'));
const backend=spawn(process.execPath,args,{env:{...process.env,PORT:String(BACKEND_PORT)},stdio:'inherit'});
backend.on('error',e=>console.error('Backend process error:',e));backend.on('exit',(code,signal)=>{console.error(`Backend stopped. code=${code} signal=${signal}`);if(!server.listening)process.exit(code||1)});
function json(res,status,data){if(res.headersSent)return;res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function serveFile(res,filePath){fs.stat(filePath,(error,stat)=>{if(error||!stat.isFile()){return json(res,404,{success:false,message:'Page not found'})}const ext=path.extname(filePath).toLowerCase();const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.webp':'image/webp'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(filePath).pipe(res)})}
function proxyApi(req,res){const requestPath=req.url;const request=http.request({hostname:'127.0.0.1',port:BACKEND_PORT,path:requestPath,method:req.method,headers:{...req.headers,host:`127.0.0.1:${BACKEND_PORT}`}},backendRes=>{res.writeHead(backendRes.statusCode||502,backendRes.headers);backendRes.pipe(res)});request.setTimeout(15000,()=>request.destroy(new Error('Backend timeout')));request.on('error',error=>{console.error('API proxy error:',error.message);json(res,502,{success:false,message:'تعذر الاتصال بالخادم الداخلي'});});req.pipe(request)}
const server=http.createServer((req,res)=>{if(req.url==='/health'||req.url==='/api/health')return json(res,200,{success:true,status:'online',backend:'internal'});if(req.url.startsWith('/api/'))return proxyApi(req,res);let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{return json(res,400,{success:false,message:'Bad request'})}if(pathname==='/'||pathname==='/index.html')return serveFile(res,path.join(ROOT,'index.html'));const relative=pathname.replace(/^\/+/, '');const filePath=path.resolve(ROOT,relative);if(filePath!==ROOT&&!filePath.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end('Forbidden')}serveFile(res,filePath)});
server.listen(PUBLIC_PORT,'0.0.0.0',()=>{console.log(`🚀 Web server listening on port ${PUBLIC_PORT}`);console.log(`🔗 Backend running internally on port ${BACKEND_PORT}`);console.log('🏫 School platform ready')});function shutdown(){server.close(()=>{});backend.kill('SIGTERM')}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);