const http=require('http');const fs=require('fs');const path=require('path');const {spawn}=require('child_process');const crypto=require('crypto');
const Database=require('better-sqlite3');
const registrationApi=require('./registration-api');
const PORT=Number(process.env.PORT||8080);const BACKEND=Number(process.env.BACKEND_PORT||8081);const ROOT=__dirname;
const child=spawn(process.execPath,[path.join(ROOT,'server.js')],{env:{...process.env,PORT:String(BACKEND),BACKEND_PORT:String(BACKEND)},stdio:'inherit'});
child.on('error',e=>console.error('Backend error:',e));child.on('exit',(c,s)=>console.error(`Backend exited code=${c} signal=${s}`));
function json(res,status,data){if(res.headersSent)return;res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function file(res,p){fs.stat(p,(e,st)=>{if(e||!st.isFile())return res.end('Not found');if(p.endsWith('.html'))return fs.readFile(p,'utf8',(er,data)=>{if(er)return res.end('Server error');const injected=data.replace('</body>','<script src="/educore-brand.js"></script><script src="/school-registration-ui.js"></script><script src="/language-selector.js"></script><script src="/employee-ui.js"></script><script src="/school-registration-admin-ui.js"></script><script src="/owner-premium-ui.js"></script><script src="/owner-control-ui.js"></script><script src="/owner-registration-ui.js"></script><script src="/public-landing-ui.js"></script></body>');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(injected)});res.writeHead(200,{'Content-Type':p.endsWith('.js')?'application/javascript':'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(p).pipe(res)})}
function dbRead(fn){const db=new Database(path.join(ROOT,'school.db'),{readonly:true});try{return fn(db)}finally{db.close()}}
function registrationOptions(req,res){try{const schools=dbRead(db=>{try{return db.prepare("SELECT id,name FROM schools WHERE status='active' ORDER BY name").all()}catch(_){return db.prepare('SELECT id,name FROM schools WHERE active=1 ORDER BY name').all()}});const roles=['معلم','معلم أول','معلم مساعد','ولي أمر','طالب','مسؤول شؤون الطلاب','مسؤول التسجيل والقبول','مسؤول الحضور والغياب','مرشد طلابي','محاسب','مسؤول الرسوم الدراسية','أمين صندوق','مسؤول الجودة','مسؤول العمليات','مسؤول الموارد البشرية','مسؤول تقنية المعلومات','مسؤول المرافق','أمين مكتبة'];json(res,200,{success:true,roles,schools})}catch(e){console.error(e);json(res,500,{success:false,message:'تعذر تحميل بيانات التسجيل'})}}
function publicSchools(req,res){try{const schools=dbRead(db=>{try{return db.prepare("SELECT id,name,description,logo FROM schools WHERE status='active' ORDER BY name").all()}catch(_){return db.prepare("SELECT id,name,description,logo FROM schools WHERE active=1 ORDER BY name").all()}});json(res,200,{success:true,schools})}catch(e){json(res,500,{success:false,message:'تعذر تحميل المدارس'})}}
function readBody(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c.toString();if(raw.length>1024*1024)reject(new Error('payload too large'))});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(e)}});req.on('error',reject)})}
function slug(v){return String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'_').replace(/^_+|_+$/g,'').slice(0,32)}
function usernameFor(fullName,role){let prefix='emp';const r=String(role||'');if(r.includes('معلم')||/teacher/i.test(r))prefix='teacher';else if(r.includes('ولي')||/parent/i.test(r))prefix='parent';else if(r.includes('طالب')||/student/i.test(r))prefix='student';else if(r.includes('مدير')||r.includes('مالك')||r.includes('مبرمج')||/owner|admin/i.test(r))prefix='admin';const name=slug(fullName)||'user';return `${prefix}_${name}`.slice(0,40)}
function uniqueUsername(fullName,role){const db=new Database(path.join(ROOT,'school.db'));try{const base=usernameFor(fullName,role);let u=base;let n=2;while(db.prepare('SELECT 1 FROM users WHERE username=?').get(u))u=`${base}_${n++}`.slice(0,40);return u}finally{db.close()}}
function hash(v){return crypto.createHash('sha256').update(String(v)).digest('hex')}
function normalizeRole(role){const aliases={'موظف إداري':'مسؤول العمليات','محاسب / مسؤول مالي':'محاسب','مشرف':'مشرف تربوي','الموارد البشرية (HR)':'مسؤول الموارد البشرية','مدرس':'معلم'};return aliases[String(role||'').trim()]||String(role||'').trim()}
const ALLOWED_ROLES=['نائب مدير المدرسة','المدير الأكاديمي','المدير الإداري','مشرف أكاديمي','مشرف تربوي','مشرف إداري','رئيس قسم','منسق أكاديمي','معلم','معلم أول','معلم مساعد','مدرس بديل','مسؤول شؤون الطلاب','مسؤول التسجيل والقبول','مسؤول الحضور والغياب','مسؤول الأنشطة الطلابية','مرشد طلابي','مدير مالي','محاسب','مسؤول الرسوم الدراسية','أمين صندوق','مدير الجودة','مسؤول الجودة','مسؤول التقييم والمتابعة','مسؤول العمليات','مسؤول الموارد البشرية','مسؤول تقنية المعلومات','مسؤول المرافق','أمين مكتبة','ولي أمر','طالب'];
function ensureRegistrationSchema(db){db.exec("CREATE TABLE IF NOT EXISTS registration_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,request_type TEXT NOT NULL DEFAULT 'user',user_id INTEGER,school_id INTEGER,full_name TEXT,email TEXT,phone TEXT,role TEXT,details TEXT,status TEXT NOT NULL DEFAULT 'pending',owner_note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)");try{db.exec('ALTER TABLE users ADD COLUMN school_id INTEGER')}catch(_){}try{db.exec('ALTER TABLE users ADD COLUMN must_change_password INTEGER DEFAULT 0')}catch(_){}try{db.exec('ALTER TABLE users ADD COLUMN active INTEGER DEFAULT 1')}catch(_){} }
function publicRegister(req,res){readBody(req).then(body=>{const b=body||{};const fullName=String(b.full_name||b.name||'').trim();const email=String(b.email||b.emailAddress||'').trim();const phone=String(b.phone||b.mobile||'').trim();const password=String(b.password||b.reg_password||b.regPassword||'').trim();const role=normalizeRole(b.role);const schoolValue=b.school_id??b.schoolId??b.school??'';const schoolName=String(b.school_name||b.schoolName||'').trim();if(!fullName||!email||!password||!role)return json(res,400,{success:false,message:'أكمل الاسم والبريد والوظيفة وكلمة المرور.'});if(!schoolValue&&!schoolName)return json(res,400,{success:false,message:'اختر المدرسة.'});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(res,400,{success:false,message:'البريد الإلكتروني غير صحيح.'});if(password.length<8||!/[A-Za-z\u0600-\u06FF]/.test(password)||!/[0-9]/.test(password))return json(res,400,{success:false,message:'كلمة المرور يجب أن تكون 8 أحرف على الأقل وتحتوي على حرف ورقم.'});if(!ALLOWED_ROLES.includes(role))return json(res,400,{success:false,message:'الوظيفة المختارة غير متاحة للتسجيل العام.'});const db=new Database(path.join(ROOT,'school.db'));try{ensureRegistrationSchema(db);let school=null;if(String(schoolValue).trim()!==''){const id=Number(schoolValue);if(Number.isInteger(id)&&id>0)school=db.prepare("SELECT id,name FROM schools WHERE id=? AND (status='active' OR active=1)").get(id)}if(!school&&schoolName)school=db.prepare("SELECT id,name FROM schools WHERE lower(name)=lower(?) AND (status='active' OR active=1)").get(schoolName);if(!school)return json(res,400,{success:false,message:'المدرسة غير موجودة أو غير معتمدة.'});if(db.prepare('SELECT id FROM users WHERE lower(email)=lower(?)').get(email))return json(res,409,{success:false,message:'هذا البريد الإلكتروني مستخدم بالفعل.'});const username=uniqueUsername(fullName,role);const tx=db.transaction(()=>{const r=db.prepare('INSERT INTO users(username,password_hash,full_name,email,phone,role,active,must_change_password,school_id) VALUES(?,?,?,?,?,?,0,1,?)').run(username,hash(password),fullName,email,phone,role,school.id);const uid=Number(r.lastInsertRowid);db.prepare("INSERT INTO registration_requests(request_type,user_id,school_id,full_name,email,phone,role,details,status) VALUES('user',?,?,?,?,?,?,?,'pending')").run(uid,school.id,fullName,email,phone,role,JSON.stringify({school_id:school.id,school_name:school.name,username}));return uid});tx();console.log(`PUBLIC USER REGISTRATION: ${username} -> ${school.name} (${role})`);return json(res,201,{success:true,message:'تم إرسال طلب التسجيل للاعتماد. احتفظ باسم المستخدم الظاهر أدناه.',username,role,school_id:school.id,school_name:school.name,status:'pending'})}catch(e){console.error('PUBLIC_REGISTER_RUNTIME',e.stack||e);return json(res,500,{success:false,message:'حدث خطأ أثناء إنشاء طلب التسجيل'})}finally{db.close()}}).catch(e=>json(res,400,{success:false,message:'بيانات التسجيل غير صالحة'}))}
function syncLocalRegistration(body,payload){try{const db=new Database(path.join(ROOT,'school.db'));const name=String(body.name||body.school_name||payload.school?.name||'').trim();let school=db.prepare('SELECT id FROM schools WHERE name=? LIMIT 1').get(name);if(!school){const r=db.prepare('INSERT INTO schools(name,description,active) VALUES(?,?,0)').run(name,body.description||'');school={id:r.lastInsertRowid}}const title=`طلب تسجيل مدرسة: ${name}`;const exists=db.prepare("SELECT 1 FROM admin_requests WHERE title=? AND school_id=? AND status='new'").get(title,school.id);if(!exists)db.prepare('INSERT INTO admin_requests(request_type,title,description,requested_by,school_id,status,priority) VALUES(?,?,?,?,?,?,?)').run('school_registration',title,JSON.stringify({applicant_name:body.applicant_name||body.manager_name||'',email:body.email||'',phone:body.phone||'',student_count:body.student_count||body.students_count||null,supabase_school_id:payload.school?.id||null,supabase_request_id:payload.request?.id||null}),null,school.id,'new','normal');db.close()}catch(e){console.error('LOCAL_REGISTRATION_SYNC',e)}}
async function schoolRegister(req,res){try{const url=String(process.env.SUPABASE_URL||'').replace(/\/$/,'');const key=String(process.env.SUPABASE_ANON_KEY||'');if(!url||!key)return json(res,503,{success:false,message:'خدمة تسجيل المدارس غير مهيأة بعد'});const body=await readBody(req);const r=await fetch(`${url}/functions/v1/school-register`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`,apikey:key},body:JSON.stringify(body)});const text=await r.text();let payload={};try{payload=JSON.parse(text)}catch(_){}if(r.ok&&payload.success)syncLocalRegistration(body,payload);res.writeHead(r.status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(text)}catch(e){console.error('SCHOOL_REGISTER_RUNTIME',e);json(res,500,{success:false,message:'تعذر تسجيل المدرسة'})}}
function proxy(req,res,bodyOverride){const headers={...req.headers,host:`127.0.0.1:${BACKEND}`};let body=null;if(bodyOverride!==undefined){body=Buffer.from(JSON.stringify(bodyOverride));headers['content-length']=body.length;delete headers['transfer-encoding']}const r=http.request({hostname:'127.0.0.1',port:BACKEND,path:req.url,method:req.method,headers},x=>{res.writeHead(x.statusCode||502,x.headers);x.pipe(res)});r.on('error',e=>json(res,502,{success:false,message:'الخادم الداخلي غير جاهز حالياً'}));if(body)r.end(body);else req.pipe(r)}
function ownerAlias(req,res,target){const u=new URL(req.url,'http://localhost');u.pathname=target;req.url=u.pathname+(u.search||'');proxy(req,res)}
function settings(req,res){try{const rows=dbRead(db=>db.prepare('SELECT key,value FROM settings ORDER BY key').all());json(res,200,{success:true,settings:rows})}catch(e){json(res,500,{success:false,message:'تعذر تحميل الإعدادات'})}}
async function api(req,res){const p=req.url.split('?')[0];if(p==='/api/public/registration-options'&&req.method==='GET')return registrationOptions(req,res);if(p==='/api/public/schools'&&req.method==='GET')return publicSchools(req,res);if(p==='/api/public/register'&&req.method==='POST')return publicRegister(req,res);if(p==='/api/public/school-register'&&req.method==='POST')return schoolRegister(req,res);if(p==='/api/owner/registration-requests'&&req.method==='GET')return registrationApi.handle(req,res);if(p==='/api/school/registration-requests'&&req.method==='GET')return registrationApi.handle(req,res);if(p.startsWith('/api/owner/registration-requests/')&&(req.method==='PATCH'||req.method==='POST'))return registrationApi.handle(req,res);if(p==='/api/owner/full-overview'&&req.method==='GET')return ownerAlias(req,res,'/api/owner/overview');if(p==='/api/owner/settings'&&req.method==='GET')return settings(req,res);if(req.method==='POST'&&(p==='/api/owner/users'||p==='/api/owner/employees')){try{const body=await readBody(req);if(body.full_name&&!body.custom_username)body.username=uniqueUsername(body.full_name,body.role);return proxy(req,res,body)}catch(e){return json(res,400,{success:false,message:'بيانات JSON غير صالحة'})}}return proxy(req,res)}
const server=http.createServer((req,res)=>{if(req.url==='/health'||req.url==='/api/health')return json(res,200,{success:true,status:'online'});if(req.url.startsWith('/api/'))return api(req,res);const p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(p==='/'||p==='/index.html')return file(res,path.join(ROOT,'index.html'));if(['/educore-brand.js','/school-registration-ui.js','/language-selector.js','/employee-ui.js','/school-registration-admin-ui.js','/owner-premium-ui.js','/owner-control-ui.js','/owner-registration-ui.js','/public-landing-ui.js','/owner-ui.js','/owner-design-ui.js','/owner-subscriptions-ui.js','/login-fix.js','/owner-dashboard.js','/hr-dashboard.js'].includes(p))return file(res,path.join(ROOT,p.slice(1)));const target=path.resolve(ROOT,p.replace(/^\/+/,''));if(target!==ROOT&&!target.startsWith(ROOT+path.sep))return res.end('Forbidden');file(res,target)});
server.listen(PORT,'0.0.0.0',()=>console.log(`🚀 EduCore Platform public server listening on ${PORT}; backend ${BACKEND}; health /health`));
function stop(){server.close();child.kill('SIGTERM')}process.on('SIGTERM',stop);process.on('SIGINT',stop);