const http=require('http');const Database=require('better-sqlite3');const path=require('path');
function db(){return new Database(path.join(__dirname,'school.db'));}
function json(res,status,data){if(res.headersSent)return;res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function readBody(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c.toString();if(raw.length>1024*1024)reject(new Error('payload too large'));});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch(e){reject(e);}});req.on('error',reject);});}
function authHeader(req){let a=req.headers.authorization||'';if(a)return a;const c=req.headers.cookie||'';const m=c.match(/(?:^|;\s*)(?:educore_token|school_token|authToken|access_token|accessToken|token|sessionToken)=([^;]+)/i);return m?'Bearer '+decodeURIComponent(m[1]):'';}
function backendMe(req){return new Promise((resolve,reject)=>{const authorization=authHeader(req);const headers={authorization};if(req.headers.cookie)headers.cookie=req.headers.cookie;const r=http.request({hostname:'127.0.0.1',port:Number(process.env.BACKEND_PORT||8081),path:'/api/auth/me',method:'GET',headers},x=>{let b='';x.on('data',c=>b+=c);x.on('end',()=>{try{resolve({status:x.statusCode||500,data:JSON.parse(b||'{}')});}catch(e){resolve({status:x.statusCode||500,data:{}});}});});r.on('error',reject);r.end();});}
async function me(req){try{const r=await backendMe(req);if(r.status!==200||!r.data.success)return null;return r.data.user||null;}catch(_){return null;}}
const OWNER=['مبرمج','مبرمج النظام','مالك المنصة','owner','OWNER'];
async function ownerGuard(req,res){const user=await me(req);if(!user)return {ok:false,res:json(res,401,{success:false,message:'جلسة الدخول غير صالحة أو منتهية. سجل الدخول للمالك من جديد.'})};if(!OWNER.includes(String(user.role||'')))return {ok:false,res:json(res,403,{success:false,message:'هذه المنطقة مخصصة لمالك المنصة'})};return {ok:true,user};}
async function ownerRequests(req,res){const g=await ownerGuard(req,res);if(!g.ok)return;const d=db();try{const rows=d.prepare("SELECT r.*,u.username,u.active,s.name school_name FROM registration_requests r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN schools s ON s.id=r.school_id ORDER BY CASE WHEN lower(r.status) IN ('new','pending') THEN 0 ELSE 1 END,r.id DESC").all();return json(res,200,{success:true,requests:rows,count:rows.filter(x=>['new','pending'].includes(String(x.status).toLowerCase())).length});}finally{d.close();}}
async function schoolRequests(req,res){const user=await me(req);if(!user)return json(res,401,{success:false,message:'جلسة الدخول غير صالحة أو منتهية'});if(!user.school_id)return json(res,403,{success:false,message:'الحساب غير مرتبط بمدرسة'});const d=db();try{const rows=d.prepare("SELECT r.*,u.username,u.active,s.name school_name FROM registration_requests r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN schools s ON s.id=r.school_id WHERE r.school_id=? AND r.request_type='user' ORDER BY r.id DESC").all(user.school_id);return json(res,200,{success:true,requests:rows,count:rows.filter(x=>['new','pending'].includes(String(x.status).toLowerCase())).length});}finally{d.close();}}
async function review(req,res){const g=await ownerGuard(req,res);if(!g.ok)return;const parts=req.url.split('?')[0].split('/').filter(Boolean);const id=Number(parts[parts.length-2]);if(!Number.isInteger(id))return json(res,400,{success:false,message:'رقم الطلب غير صحيح'});const body=await readBody(req).catch(()=>({}));let decision=String(body.decision||body.action||body.status||'').toLowerCase();if(['approve','approved','accept','accepted','قبول','مقبول'].includes(decision))decision='approved';else if(['reject','rejected','decline','declined','رفض','مرفوض'].includes(decision))decision='rejected';else return json(res,400,{success:false,message:'حدد القرار: approved أو rejected'});const d=db();try{const r=d.prepare('SELECT * FROM registration_requests WHERE id=?').get(id);if(!r)return json(res,404,{success:false,message:'طلب التسجيل غير موجود'});const tx=d.transaction(()=>{if(decision==='approved'){if(r.user_id)d.prepare('UPDATE users SET active=1,must_change_password=1 WHERE id=?').run(r.user_id);if(r.school_id){const cols=d.prepare('PRAGMA table_info(schools)').all().map(x=>x.name);if(cols.includes('active'))d.prepare('UPDATE schools SET active=1 WHERE id=?').run(r.school_id);if(r.request_type==='school'&&r.user_id)d.prepare('UPDATE users SET school_id=?,role=?,active=1 WHERE id=?').run(r.school_id,'مدير',r.user_id);}}else if(r.user_id)d.prepare('UPDATE users SET active=0 WHERE id=?').run(r.user_id);d.prepare('UPDATE registration_requests SET status=?,owner_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(decision,body.decision_note||body.note||'',id);});tx();return json(res,200,{success:true,message:decision==='approved'?'تم اعتماد الطلب وتفعيل الحساب وربطه بالمدرسة':'تم رفض الطلب',status:decision});}catch(e){console.error('REG_REVIEW',e);return json(res,500,{success:false,message:'تعذر تنفيذ الطلب',error:e.message});}finally{d.close();}}
async function approveEmployee(req,res,decision){const user=await me(req);if(!user)return json(res,401,{success:false,message:'جلسة الدخول غير صالحة أو منتهية'});if(!user.school_id)return json(res,403,{success:false,message:'الحساب غير مرتبط بمدرسة'});const parts=req.url.split('?')[0].split('/').filter(Boolean);const id=Number(parts[parts.length-1]);if(!Number.isInteger(id))return json(res,400,{success:false,message:'رقم الطلب غير صحيح'});const d=db();try{const r=d.prepare("SELECT * FROM registration_requests WHERE id=? AND school_id=? AND request_type='user'").get(id,user.school_id);if(!r)return json(res,404,{success:false,message:'طلب الموظف غير موجود'});d.prepare('UPDATE users SET active=? WHERE id=? AND school_id=?').run(decision==='approved'?1:0,r.user_id,user.school_id);d.prepare('UPDATE registration_requests SET status=?,owner_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(decision,'',id);return json(res,200,{success:true,message:decision==='approved'?'تم اعتماد الموظف':'تم رفض الموظف',status:decision});}finally{d.close();}}
async function handle(req,res){const p=req.url.split('?')[0];if(p==='/api/owner/registration-requests'&&req.method==='GET')return ownerRequests(req,res);if(p==='/api/school/registration-requests'&&req.method==='GET')return schoolRequests(req,res);if(p.match(/^\/api\/owner\/registration-requests\/\d+\/review$/)&&(req.method==='POST'||req.method==='PATCH'))return review(req,res);if(p.match(/^\/api\/school\/registration-requests\/\d+\/(approve|reject)$/)&&req.method==='POST')return approveEmployee(req,res,p.endsWith('/approve')?'approved':'rejected');return false;}
module.exports={handle};