const http = require('http');
const Database = require('better-sqlite3');
const path = require('path');

function db(){ return new Database(path.join(__dirname,'school.db')); }
function json(res,status,data){ if(res.headersSent)return; res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'}); res.end(JSON.stringify(data)); }
function readBody(req){ return new Promise((resolve,reject)=>{let raw=''; req.on('data',c=>{raw+=c.toString(); if(raw.length>1024*1024) reject(new Error('payload too large'));}); req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch(e){reject(e);}}); req.on('error',reject);}); }
function backendMe(req){ return new Promise((resolve,reject)=>{const r=http.request({hostname:'127.0.0.1',port:Number(process.env.BACKEND_PORT||8081),path:'/api/auth/me',method:'GET',headers:{authorization:req.headers.authorization||''}},x=>{let b='';x.on('data',c=>b+=c);x.on('end',()=>{try{resolve({status:x.statusCode||500,data:JSON.parse(b||'{}')});}catch(e){resolve({status:x.statusCode||500,data:{}});}});});r.on('error',reject);r.end();}); }
async function me(req,res){try{const r=await backendMe(req);if(r.status!==200||!r.data.success)return null;return r.data.user||null;}catch(_){return null;}}
async function ownerRequests(req,res){const user=await me(req);if(!user)return json(res,401,{success:false,message:'يجب تسجيل الدخول أولاً'});if(!['مبرمج','مبرمج النظام','مالك المنصة','owner'].includes(user.role))return json(res,403,{success:false,message:'هذه المنطقة مخصصة لمالك المنصة'});const d=db();try{const rows=d.prepare("SELECT r.*,s.name school_name FROM admin_requests r LEFT JOIN schools s ON s.id=r.school_id WHERE r.request_type='school_registration' ORDER BY r.id DESC").all();return json(res,200,{success:true,requests:rows});}finally{d.close();}}
async function schoolRequests(req,res){const user=await me(req);if(!user)return json(res,401,{success:false,message:'يجب تسجيل الدخول أولاً'});if(!user.school_id)return json(res,403,{success:false,message:'الحساب غير مرتبط بمدرسة'});const d=db();try{const rows=d.prepare("SELECT r.*,s.name school_name FROM admin_requests r LEFT JOIN schools s ON s.id=r.school_id WHERE r.request_type='school_registration' AND r.school_id=? ORDER BY r.id DESC").all(user.school_id);return json(res,200,{success:true,requests:rows});}finally{d.close();}}
async function approve(req,res){const user=await me(req);if(!user)return json(res,401,{success:false,message:'يجب تسجيل الدخول أولاً'});if(!['مبرمج','مبرمج النظام','مالك المنصة','owner'].includes(user.role))return json(res,403,{success:false,message:'هذه العملية للمالك فقط'});const id=Number(req.url.split('/').pop());if(!Number.isInteger(id))return json(res,400,{success:false,message:'رقم الطلب غير صحيح'});const body=await readBody(req).catch(()=>({}));const d=db();try{const r=d.prepare("SELECT * FROM admin_requests WHERE id=? AND request_type='school_registration'").get(id);if(!r)return json(res,404,{success:false,message:'طلب التسجيل غير موجود'});d.prepare("UPDATE admin_requests SET status=?,decision_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(body.status||'approved',body.decision_note||'',id);if((body.status||'approved')==='approved'&&r.school_id)d.prepare('UPDATE schools SET active=1 WHERE id=?').run(r.school_id);return json(res,200,{success:true,message:'تم تحديث طلب التسجيل',status:body.status||'approved'});}finally{d.close();}}
async function handle(req,res){const p=req.url.split('?')[0];if(p==='/api/owner/registration-requests'&&req.method==='GET')return ownerRequests(req,res);if(p==='/api/school/registration-requests'&&req.method==='GET')return schoolRequests(req,res);if(p.startsWith('/api/owner/registration-requests/')&&(req.method==='PATCH'||req.method==='POST'))return approve(req,res);return false;}
module.exports={handle};
