const express = require('express');
const Database = require('better-sqlite3');
const path = require('path');
const crypto = require('crypto');
const originalUse = express.application.use;
const originalListen = express.application.listen;
let ownerAuth = null;
express.application.use = function(p,...h){if(p==='/api/owner'&&typeof h[0]==='function') ownerAuth=h[0]; return originalUse.call(this,p,...h)};
express.application.listen = function(...args){
 const app=this;
 if(ownerAuth&&!app.__registrationFix){app.__registrationFix=true;
  const db=new Database(path.join(__dirname,'school.db')); db.pragma('foreign_keys = ON');
  const owner=(req,res,next)=>['مبرمج','مبرمج النظام','مالك المنصة','owner'].includes(req.user?.role)?next():res.status(403).json({success:false,message:'هذه العملية مخصصة لمالك المنصة'});
  const manager=(req,res,next)=>['مدير','مدير المدرسة'].includes(req.user?.role)?next():res.status(403).json({success:false,message:'هذه العملية مخصصة لمدير المدرسة'});
  app.post('/api/registration-requests',(req,res)=>{try{const b=req.body||{};if(!b.full_name||!b.username||!b.password||!b.school_name)return res.status(400).json({success:false,message:'الاسم واسم المستخدم وكلمة المرور واسم المدرسة مطلوبة'});if(db.prepare('SELECT id FROM users WHERE username=?').get(String(b.username).trim()))return res.status(409).json({success:false,message:'اسم المستخدم مستخدم بالفعل'});const r=db.prepare('INSERT INTO admin_requests(request_type,title,description,status,priority) VALUES(?,?,?,?,?)').run('manager_registration',`طلب تسجيل مدير مدرسة: ${b.school_name}`,JSON.stringify({full_name:b.full_name,username:b.username,password:b.password,email:b.email||'',phone:b.phone||'',school_name:b.school_name,school_description:b.school_description||''}),'new','normal');res.status(201).json({success:true,id:r.lastInsertRowid,status:'new',message:'تم إرسال طلب التسجيل للمالك'});}catch(e){console.error(e);res.status(500).json({success:false,message:'تعذر إرسال طلب التسجيل'})}});
  app.get('/api/owner/registration-requests',ownerAuth,owner,(req,res)=>{try{const rows=db.prepare("SELECT r.*,u.full_name requester_name,sc.name school_name FROM admin_requests r LEFT JOIN users u ON u.id=r.requested_by LEFT JOIN schools sc ON sc.id=r.school_id WHERE r.request_type IN ('manager_registration','admin_registration','مدير مدرسة') ORDER BY r.id DESC").all();res.json({success:true,requests:rows});}catch(e){res.status(500).json({success:false,message:'تعذر تحميل طلبات التسجيل'})}});
  app.post('/api/owner/registration-requests/:id/review',ownerAuth,owner,(req,res)=>{try{const b=req.body||{};if(!['approved','rejected'].includes(String(b.status)))return res.status(400).json({success:false,message:'حالة الطلب غير صحيحة'});const r=db.prepare("SELECT * FROM admin_requests WHERE id=? AND request_type IN ('manager_registration','admin_registration','مدير مدرسة')").get(req.params.id);if(!r)return res.status(404).json({success:false,message:'الطلب غير موجود'});if(b.status==='rejected'){db.prepare('UPDATE admin_requests SET status=?,decision_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run('rejected',b.decision_note||'',r.id);return res.json({success:true,status:'rejected'});}const d=JSON.parse(r.description||'{}');let schoolId=r.school_id;if(!schoolId){schoolId=db.prepare('INSERT INTO schools(name,description) VALUES(?,?)').run(d.school_name||r.title,d.school_description||'').lastInsertRowid;}const hash=p=>crypto.createHash('sha256').update(String(p)).digest('hex');let u=db.prepare('SELECT id FROM users WHERE username=?').get(d.username);if(u)db.prepare("UPDATE users SET full_name=?,email=?,phone=?,role='مدير',active=1,school_id=?,must_change_password=1,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(d.full_name||d.username,d.email||'',d.phone||'',schoolId,u.id);else u={id:db.prepare("INSERT INTO users(username,password_hash,full_name,email,phone,role,active,must_change_password,school_id) VALUES(?,?,?,?,?,'مدير',1,1,?)").run(d.username,hash(d.password||''),d.full_name||d.username,d.email||'',d.phone||'',schoolId).lastInsertRowid};db.prepare('UPDATE admin_requests SET status=?,school_id=?,decision_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run('approved',schoolId,b.decision_note||'تم الاعتماد',r.id);res.json({success:true,status:'approved',school_id:schoolId,user_id:u.id});}catch(e){console.error(e);res.status(500).json({success:false,message:'تعذر اعتماد الطلب'})}});
  app.get('/api/manager/employee-requests',ownerAuth,manager,(req,res)=>{try{const rows=db.prepare("SELECT r.*,u.full_name requester_name FROM admin_requests r LEFT JOIN users u ON u.id=r.requested_by WHERE r.school_id=? AND r.request_type IN ('employee_registration','staff_registration','موظف') ORDER BY r.id DESC").all(req.user.school_id);res.json({success:true,requests:rows});}catch(e){res.status(500).json({success:false,message:'تعذر تحميل طلبات الموظفين'})}});
  app.patch('/api/manager/employee-requests/:id',ownerAuth,manager,(req,res)=>{try{const b=req.body||{};if(!['approved','rejected'].includes(String(b.status)))return res.status(400).json({success:false,message:'حالة الطلب غير صحيحة'});const r=db.prepare("UPDATE admin_requests SET status=?,decision_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND school_id=? AND request_type IN ('employee_registration','staff_registration','موظف')").run(b.status,b.decision_note||'',req.params.id,req.user.school_id);if(!r.changes)return res.status(404).json({success:false,message:'الطلب غير موجود أو لا يتبع لمدرستك'});res.json({success:true});}catch(e){res.status(500).json({success:false,message:'تعذر تحديث الطلب'})}});
 }
 return originalListen.apply(this,args);
};
