const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const Database=require('better-sqlite3');
const Module=require('module');
const originalLoad=Module._load;
const DB_PATH=path.join(__dirname,'school.db');
const BACKUP_DIR=path.join(__dirname,'backups');
const sessions=new Map();
const RESET_TTL=30*60*1000;
const resetTokens=new Map();

function scrypt(password,salt=crypto.randomBytes(16).toString('hex')){return `scrypt$${salt}$${crypto.scryptSync(String(password),salt,64).toString('hex')}`}
function verify(password,stored){
  if(!stored)return false;
  if(stored.startsWith('scrypt$')){const [,salt,hex]=stored.split('$');const got=crypto.scryptSync(String(password),salt,64);return crypto.timingSafeEqual(got,Buffer.from(hex,'hex'))}
  return stored===crypto.createHash('sha256').update(String(password)).digest('hex');
}
function b32decode(s){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='',out=[];for(const c of String(s).replace(/=+$/,'').toUpperCase()){const n=alphabet.indexOf(c);if(n<0)continue;bits+=n.toString(2).padStart(5,'0')}for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(out)}
function totp(secret,step=Math.floor(Date.now()/30000)){const key=b32decode(secret);const b=Buffer.alloc(8);let n=step;for(let i=7;i>=0;i--){b[i]=n&255;n=Math.floor(n/256)}const h=crypto.createHmac('sha1',key).update(b).digest();const o=h[h.length-1]&15;const code=((h.readUInt32BE(o)&0x7fffffff)%1000000).toString().padStart(6,'0');return code}
function validTotp(secret,code){const c=String(code||'');for(let d=-1;d<=1;d++)if(totp(secret,Math.floor(Date.now()/30000)+d)===c)return true;return false}
function secret(){let s='';const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';for(let i=0;i<16;i++)s+=alphabet[crypto.randomInt(alphabet.length)];return s}
function audit(db,userId,action,details=''){db.prepare('INSERT INTO audit_logs(user_id,action,details) VALUES(?,?,?)').run(userId||null,action,details)}

Module._load=function(request,parent,isMain){const loaded=originalLoad.apply(this,arguments);if(request!=='express')return loaded;function wrappedExpress(){const app=loaded();const db=new Database(DB_PATH);db.pragma('foreign_keys=ON');db.exec(`
CREATE TABLE IF NOT EXISTS security_2fa (user_id INTEGER PRIMARY KEY, secret TEXT NOT NULL, enabled INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS password_resets (token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL,used INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS backup_log (id INTEGER PRIMARY KEY AUTOINCREMENT,file_name TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,size INTEGER DEFAULT 0);
`);

// Strong password hashing on every new password. Existing SHA-256 hashes are upgraded after successful login.
app.use('/api/auth/login',(req,res,next)=>{if(req.method!=='POST')return next();const {username,password,otp}=req.body||{};if(!username||!password)return next();const user=db.prepare('SELECT * FROM users WHERE username=?').get(String(username).trim());if(!user||!user.active)return next();if(!verify(password,user.password_hash))return next();const sensitive=['مبرمج','مدير','مدير المدرسة'].includes(user.role);const factor=db.prepare('SELECT * FROM security_2fa WHERE user_id=?').get(user.id);if(sensitive&&factor?.enabled){if(!validTotp(factor.secret,otp))return res.status(401).json({success:false,code:'2FA_REQUIRED',message:'مطلوب رمز المصادقة الثنائية للحساب الحساس'});}
if(!String(user.password_hash).startsWith('scrypt$'))db.prepare('UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(scrypt(password),user.id);
const token=crypto.randomBytes(32).toString('hex');req.__securityLogin={token,user};audit(db,user.id,'login_secure',sensitive?'2FA verified':'password verified');return res.json({success:true,token,user:{id:user.id,username:user.username,full_name:user.full_name,email:user.email,phone:user.phone,role:user.role,must_change_password:Boolean(user.must_change_password)},security:{two_factor_required:Boolean(sensitive&&factor?.enabled)}})
});

app.post('/api/security/2fa/setup',(req,res)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const session=req.__securitySession||null;let userId=session?.userId;if(!userId){const s=global.__educoreSessions?.get(token);userId=s?.userId}if(!userId)return res.status(401).json({success:false,message:'يجب تسجيل الدخول أولاً'});const u=db.prepare('SELECT id,username,role FROM users WHERE id=?').get(userId);if(!u)return res.status(401).json({success:false,message:'الحساب غير موجود'});const sec=secret();db.prepare('INSERT INTO security_2fa(user_id,secret,enabled) VALUES(?,?,0) ON CONFLICT(user_id) DO UPDATE SET secret=excluded.secret,enabled=0,updated_at=CURRENT_TIMESTAMP').run(u.id,sec);audit(db,u.id,'2fa_setup_started');res.json({success:true,secret:sec,issuer:'EduCore Platform',account:u.username,message:'احفظ السر ثم أكد رمز المصادقة من تطبيق Authenticator'})});
app.post('/api/security/2fa/enable',(req,res)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const s=global.__educoreSessions?.get(token);if(!s)return res.status(401).json({success:false,message:'يجب تسجيل الدخول أولاً'});const row=db.prepare('SELECT secret FROM security_2fa WHERE user_id=?').get(s.userId);if(!row||!validTotp(row.secret,req.body?.otp))return res.status(400).json({success:false,message:'رمز المصادقة غير صحيح'});db.prepare('UPDATE security_2fa SET enabled=1,updated_at=CURRENT_TIMESTAMP WHERE user_id=?').run(s.userId);audit(db,s.userId,'2fa_enabled');res.json({success:true,message:'تم تفعيل المصادقة الثنائية'})});
app.post('/api/security/2fa/disable',(req,res)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const s=global.__educoreSessions?.get(token);if(!s)return res.status(401).json({success:false,message:'يجب تسجيل الدخول أولاً'});const u=db.prepare('SELECT role FROM users WHERE id=?').get(s.userId);if(!['مبرمج','مدير','مدير المدرسة'].includes(u?.role))return res.status(403).json({success:false,message:'المصادقة الثنائية مطلوبة للحسابات الحساسة'});if(!validTotp(db.prepare('SELECT secret FROM security_2fa WHERE user_id=?').get(s.userId)?.secret,req.body?.otp))return res.status(400).json({success:false,message:'رمز المصادقة غير صحيح'});db.prepare('UPDATE security_2fa SET enabled=0,updated_at=CURRENT_TIMESTAMP WHERE user_id=?').run(s.userId);audit(db,s.userId,'2fa_disabled');res.json({success:true,message:'تم تعطيل المصادقة الثنائية'})});

app.post('/api/enterprise/reset/request',(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();if(!email)return res.status(400).json({success:false,message:'البريد الإلكتروني مطلوب'});const user=db.prepare('SELECT id,email,full_name FROM users WHERE lower(email)=?').get(email);if(!user)return res.json({success:true,message:'إذا كان البريد مسجلاً فسيتم إرسال رابط الاستعادة'});const raw=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(raw).digest('hex'),expires=Date.now()+RESET_TTL;db.prepare('INSERT INTO password_resets(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash,user.id,expires);resetTokens.set(raw,{userId:user.id,expires});const base=process.env.PUBLIC_BASE_URL||'';const link=`${base}/reset-password?token=${raw}`;const nodemailer=(()=>{try{return require('nodemailer')}catch{return null}})();if(nodemailer&&process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS){const t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_PORT)==='465',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});t.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:user.email,subject:'EduCore Platform — استعادة كلمة المرور',html:`<p>مرحباً ${user.full_name}</p><p>استخدم الرابط التالي لاستعادة كلمة المرور، وصلاحيته 30 دقيقة:</p><p><a href="${link}">${link}</a></p>`}).catch(()=>{})}else console.log('PASSWORD RESET LINK:',link);audit(db,user.id,'password_reset_requested');res.json({success:true,message:'تم إنشاء طلب الاستعادة. تحقق من بريدك الإلكتروني.'})});
app.post('/api/enterprise/reset/confirm',(req,res)=>{const token=String(req.body?.token||''),password=String(req.body?.password||'');if(password.length<10)return res.status(400).json({success:false,message:'كلمة المرور يجب أن تكون 10 أحرف على الأقل'});const hash=crypto.createHash('sha256').update(token).digest('hex');const row=db.prepare('SELECT * FROM password_resets WHERE token_hash=? AND used=0 AND expires_at>?').get(hash,Date.now());if(!row)return res.status(400).json({success:false,message:'رابط الاستعادة غير صالح أو منتهي'});db.prepare('UPDATE users SET password_hash=?,must_change_password=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(scrypt(password),row.user_id);db.prepare('UPDATE password_resets SET used=1 WHERE token_hash=?').run(hash);audit(db,row.user_id,'password_reset_completed');res.json({success:true,message:'تم تغيير كلمة المرور بنجاح'})});

app.post('/api/security/backup',(req,res)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const s=global.__educoreSessions?.get(token);if(!s)return res.status(401).json({success:false,message:'يجب تسجيل الدخول أولاً'});const u=db.prepare('SELECT role FROM users WHERE id=?').get(s.userId);if(u?.role!=='مبرمج')return res.status(403).json({success:false,message:'صلاحية المبرمج مطلوبة'});fs.mkdirSync(BACKUP_DIR,{recursive:true});const name=`educore-${new Date().toISOString().replace(/[:.]/g,'-')}.db`;const out=path.join(BACKUP_DIR,name);db.backup(out).then(()=>{const size=fs.statSync(out).size;db.prepare('INSERT INTO backup_log(file_name,size) VALUES(?,?)').run(name,size);audit(db,s.userId,'backup_created',name);res.json({success:true,file:name,size,message:'تم إنشاء النسخة الاحتياطية'})}).catch(e=>res.status(500).json({success:false,message:'تعذر إنشاء النسخة الاحتياطية'}))});
app.get('/api/security/backups',(req,res)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const s=global.__educoreSessions?.get(token);if(!s)return res.status(401).json({success:false,message:'يجب تسجيل الدخول أولاً'});const u=db.prepare('SELECT role FROM users WHERE id=?').get(s.userId);if(u?.role!=='مبرمج')return res.status(403).json({success:false,message:'صلاحية المبرمج مطلوبة'});res.json({success:true,backups:db.prepare('SELECT * FROM backup_log ORDER BY id DESC').all()})});

const interval=setInterval(()=>{try{fs.mkdirSync(BACKUP_DIR,{recursive:true});const name=`auto-${new Date().toISOString().replace(/[:.]/g,'-')}.db`;const out=path.join(BACKUP_DIR,name);db.backup(out).then(()=>{const size=fs.statSync(out).size;db.prepare('INSERT INTO backup_log(file_name,size) VALUES(?,?)').run(name,size);const rows=db.prepare('SELECT file_name FROM backup_log ORDER BY id DESC').all();for(const x of rows.slice(7)){try{fs.unlinkSync(path.join(BACKUP_DIR,x.file_name))}catch{}}db.prepare('DELETE FROM backup_log WHERE id NOT IN (SELECT id FROM backup_log ORDER BY id DESC LIMIT 7)').run()}).catch(()=>{})}catch{}} ,24*60*60*1000);interval.unref();
return app}return wrappedExpress};
